import { ApiProperty } from '@nestjs/swagger';
import { CreateRentalDto } from '../../core/app/dtos/create-rental.dto';

/**
 * Web-layer implementation of CreateRentalDto.
 * Extends the domain DTO to add Swagger documentation without polluting the core logic.
 */
export class CreateRentalWebDto extends CreateRentalDto {
  
  @ApiProperty({ 
    example: 'Vinicius', 
    description: 'First name of the client',
    minLength: 3,
    maxLength: 128 
  })
  declare clientFirstName: string;

  @ApiProperty({ 
    example: 'Berger', 
    description: 'Last name of the client',
    minLength: 3,
    maxLength: 128 
  })
  declare clientLastName: string;

  @ApiProperty({ 
    example: '2026-02-23', 
    description: 'Rental start date in ISO8601 format' 
  })
  declare startDate: string;

  @ApiProperty({ 
    example: '2026-02-28', 
    description: 'Rental end date in ISO8601 format' 
  })
  declare endDate: string;

  @ApiProperty({ 
    example: 250.75, 
    description: 'Total revenue generated by this rental' 
  })
  declare revenue: number;
}